life inprovements: need to double the bing chilling effect
Du-ma/webhook_tests pull request #8
Opened 2022-03-04 12:13 UTC by Du-ma

2022-03-25 14:30 UTC, Du-ma commented
asd

2022-03-25 14:31 UTC, Du-ma commented
ad

2022-03-25 14:33 UTC, Du-ma commented
asd

2022-03-25 15:19 UTC, Du-ma commented
asd

2022-03-25 15:45 UTC, Du-ma commented
[SC](https://soundcloud.com)
**BIM**
# BAM
`kodelis`
```python
print("kodukas")
```

2022-03-25 15:45 UTC, Du-ma commented
helou?

2022-03-25 15:46 UTC, Du-ma commented
[SC](https://soundcloud.com)
**BIM**
# BAM
`kodelis`
```python
print("kodukas")
```

2022-03-25 16:20 UTC, Du-ma commented
[SC](https://soundcloud.com)
**BIM**
# BAM
`kodelis`
```python
print("kodukas")
```

2022-03-25 16:23 UTC, gaikaz commented
![Peek 2022-03-25 18-23](https://user-images.githubusercontent.com/17097810/160160995-650cc6ea-73f3-49a1-9ffa-efa54a65388c.gif)

2022-03-25 16:23 UTC, Du-ma commented
![Peek 2022-03-25 18-23](https://user-images.githubusercontent.com/47658025/160161005-9a95db2e-5a1c-4b8e-a423-747caeb065c4.gif)

2022-03-25 16:25 UTC, gaikaz commented
https://user-images.githubusercontent.com/17097810/160161291-53d33930-4b86-4fa8-ba4b-3590b6adf334.mp4

2022-03-25 16:26 UTC, gaikaz commented
321?

2022-03-25 16:26 UTC, gaikaz commented
https://user-images.githubusercontent.com/17097810/160161466-e588e9d2-566c-4f16-9dbc-090444fe3b05.mp4

2022-03-28 13:52 UTC, Du-ma commented
ayy

2022-03-28 13:57 UTC, Mantux11 approved these changes

2022-03-28 13:58 UTC, husq570 requested changes

2022-03-28 13:58 UTC, husq570 commented on bing_chilling_file.py
> +print("BING CHILLING")
asdasd

2022-03-28 13:58 UTC, gaikaz commented on bing_chilling_file.py
> +print("BING CHILLING")
```suggestion
print("BING NETFLIX AND CHILLING")
```

2022-03-29 08:20 UTC, Mantux11 requested changes
Pimpampufpuf

2022-03-29 08:20 UTC, Mantux11 commented
dssddsd

2022-03-29 08:20 UTC, Mantux11 commented
fsdfdsfsd

2022-03-29 08:21 UTC, Mantux11 reviewed
fsddsfsd

2022-03-29 09:26 UTC, Du-ma commented
asd

2022-03-29 09:46 UTC, Du-ma commented
oiu

2022-03-29 10:55 UTC, Du-ma commented
asd

2022-03-29 10:55 UTC, Du-ma commented
adadssad

2022-03-29 10:57 UTC, Du-ma commented
asd

2022-03-29 10:58 UTC, Du-ma commented
dsdsdsdsds

2022-03-29 13:37 UTC, husq570 commented
![whatcha-doin](https://user-images.githubusercontent.com/16793949/160623895-46d51deb-fd3b-4478-a33e-b7cf87ddde76.jpg)

2022-03-29 14:39 UTC, Du-ma commented
asd

2022-03-29 15:04 UTC, Du-ma commented
asd

2022-03-30 09:14 UTC, Du-ma commented
:)

2022-03-30 09:16 UTC, Du-ma commented
:penguin:

2022-03-30 09:17 UTC, Du-ma commented
Oupen sezamy

2022-03-30 10:57 UTC, merged